#include <sys/types.h>
#include <stdlib.h>
#include <stdio.h>

int main(){
	int array[10];
	int counts[5];

	for(int i=0;i<10; i++){
		counts[i] = 0;

	}
	printf("Values received via piping ");
	
	//accumulating all values via piping
	for(int i=0; i<10;i++){
		int element;
		scanf("%d", &element);
		array[i] = element;
	}

	//prints the sequence of integers randomly generated by the producer program
	for(int i=0;i<10; i++){
		if(i==9){
			printf("%d", array[i]);
		}
		else{
			printf("%d,", array[i]);
		}
	}
	printf("\n");

	//counts the number of occurrences for each value in the array
	for(int i=0 ; i<10; i++){
		if(array[i]==3){
			counts[0]++;
		}
		else if(array[i]==4){
			counts[1]++;
		}
		else if(array[i]==5){
			counts[2]++;
		}
		else if(array[i]==6){
			counts[3]++;
		}
		else if(array[i] == 7){
			counts[4]++;
		}
	}

	int currentValue=3;
	int j=0;
	//outer loop in charge of traversing the counts array which contain the amount of occurrences per number
	while(currentValue<8){
		int index=0;
		printf("%d: ", currentValue);
		//inner loop in charge of printing the amount of occurrences the number has been generated throughout the sequencee
		while(index<counts[j]){
			index++;
			printf("*");
		}
		printf(" \n");
		j++;
		currentValue++;
	}
	return 0;
}

